# Introduction
This is one of my data analysis project that I decided to do it to practice my analysis skills.

## Dataset
Download link: [Data on Startup Companies, Investments, and Accquisitions](https://github.com/notpeter/crunchbase-data/archive/master.zip)

Source: Crunchbase

Short description: Crunchbase data contains crowndsourced information on a large number of startups including who invested in them and how much. This data which I'm going to use includes: 

* **Companies** across the world that have raised money

* **Investors** that have invested in those startups.

* **Acquisittions**

## Import packages

In [ ]:
%load_ext sql
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
%matplotlib inline
%sql sqlite://

'Connected: @None'

## Load data

In [ ]:
acquisitions = pd.read_csv('acquisitions.csv')
companies = pd.read_csv('companies.csv')
investments = pd.read_csv('investments.csv')

## Data Cleaning

### Acquistions

In [ ]:
acquisitions.head()

                                   company_permalink  ... price_currency_code
0                               /organization/003-ru  ...                 USD
1                      /organization/0958572-b-c-ltd  ...                 USD
2                 /organization/1-800-communications  ...                 USD
3                       /organization/1-800-contacts  ...                 USD
4  /organization/1-844-446-4460-pogo-customer-ser...  ...                 USD

[5 rows x 18 columns]

In [ ]:
# Brief infomation about data
acquisitions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18968 entries, 0 to 18967
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   company_permalink       18968 non-null  object
 1   company_name            18968 non-null  object
 2   company_category_list   13985 non-null  object
 3   company_country_code    14300 non-null  object
 4   company_state_code      14020 non-null  object
 5   company_region          14058 non-null  object
 6   company_city            14058 non-null  object
 7   acquirer_permalink      18968 non-null  object
 8   acquirer_name           18968 non-null  object
 9   acquirer_category_list  16580 non-null  object
 10  acquirer_country_code   17798 non-null  object
 11  acquirer_state_code     17533 non-null  object
 12  acquirer_region         17609 non-null  object
 13  acquirer_city           17609 non-null  object
 14  acquired_at             18956 non-null  object
 15  acquired_month          18954 non-null  object
 16  price_amount            5012 non-null   float64
 17  price_currency_code     18962 non-null  object
dtypes: float64(1), object(17)
memory usage: 2.6+ MB

In [ ]:
# Get dimensions of acquisitions data
acquisitions.shape

(18968, 18)

In [ ]:
#Number of missing values in acquisitions data
acquisitions.isnull().sum().sum()

46118

In [ ]:
# Drop of missing values
acquisitions.dropna(inplace = True)

In [ ]:
# Reset index after drop
acquisitions = acquisitions.reset_index(drop = True)

In [ ]:
acquisitions

                         company_permalink  ... price_currency_code
0                   /organization/1010data  ...                 USD
1                /organization/170-systems  ...                 USD
2         /organization/1st-united-bancorp  ...                 USD
3     /organization/21st-century-insurance  ...                 USD
4            /organization/24-7-real-media  ...                 USD
...                                    ...  ...                 ...
3476                  /organization/zulily  ...                 USD
3477        /organization/zygo-corporation  ...                 USD
3478                  /organization/zystor  ...                 USD
3479             /organization/zytex-group  ...                 USD
3480      /organization/’compass-solutions  ...                 USD

[3481 rows x 18 columns]

### Companies

In [ ]:
companies.head()

                             permalink  ... last_funding_at
0                  /organization/-fame  ...      2015-01-05
1               /organization/-qounter  ...      2014-10-14
2  /organization/-the-one-of-them-inc-  ...      2014-01-30
3                /organization/0-6-com  ...      2008-03-19
4       /organization/004-technologies  ...      2014-07-24

[5 rows x 14 columns]

In [ ]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   permalink          66368 non-null  object
 1   name               66367 non-null  object
 2   homepage_url       61310 non-null  object
 3   category_list      63220 non-null  object
 4   funding_total_usd  66368 non-null  object
 5   status             66368 non-null  object
 6   country_code       59410 non-null  object
 7   state_code         57821 non-null  object
 8   region             58338 non-null  object
 9   city               58340 non-null  object
 10  funding_rounds     66368 non-null  int64
 11  founded_at         51147 non-null  object
 12  first_funding_at   66344 non-null  object
 13  last_funding_at    66368 non-null  object
dtypes: int64(1), object(13)
memory usage: 7.1+ MB

**Notice that funding_total_usd column must be integer or float instead of object type.**

In [ ]:
# Check non-numeric values in funding_total_usd column
companies['funding_total_usd'].str.isnumeric()

0         True
1         True
2         True
3         True
4        False
         ...
66363     True
66364     True
66365    False
66366     True
66367     True
Name: funding_total_usd, Length: 66368, dtype: bool

**There are some False values, so it must have some character in it**.

In [ ]:
# Filter all non-numeric values.
companies = companies[companies['funding_total_usd'].str.isnumeric()].reset_index(drop = True)

In [ ]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52645 entries, 0 to 52644
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   permalink          52645 non-null  object
 1   name               52644 non-null  object
 2   homepage_url       49357 non-null  object
 3   category_list      51851 non-null  object
 4   funding_total_usd  52645 non-null  object
 5   status             52645 non-null  object
 6   country_code       48227 non-null  object
 7   state_code         47017 non-null  object
 8   region             47393 non-null  object
 9   city               47395 non-null  object
 10  funding_rounds     52645 non-null  int64
 11  founded_at         41196 non-null  object
 12  first_funding_at   52624 non-null  object
 13  last_funding_at    52645 non-null  object
dtypes: int64(1), object(13)
memory usage: 5.6+ MB

**However, there are still having missing values. It needed to be eliminated as well.**

In [ ]:
# Drop missing values and set inplace = True
companies.dropna(inplace = True)

In [ ]:
# After dropna, the indexes are not in order so it needed to be reset.
companies = companies.reset_index(drop = True)

In [ ]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36045 entries, 0 to 36044
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   permalink          36045 non-null  object
 1   name               36045 non-null  object
 2   homepage_url       36045 non-null  object
 3   category_list      36045 non-null  object
 4   funding_total_usd  36045 non-null  object
 5   status             36045 non-null  object
 6   country_code       36045 non-null  object
 7   state_code         36045 non-null  object
 8   region             36045 non-null  object
 9   city               36045 non-null  object
 10  funding_rounds     36045 non-null  int64
 11  founded_at         36045 non-null  object
 12  first_funding_at   36045 non-null  object
 13  last_funding_at    36045 non-null  object
dtypes: int64(1), object(13)
memory usage: 3.9+ MB

**Convert "funding_total_usd" back to integer.**

In [ ]:
companies['funding_total_usd'] = companies['funding_total_usd'].astype(int)

In [ ]:
# Use info() to check again
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36045 entries, 0 to 36044
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   permalink          36045 non-null  object
 1   name               36045 non-null  object
 2   homepage_url       36045 non-null  object
 3   category_list      36045 non-null  object
 4   funding_total_usd  36045 non-null  int64
 5   status             36045 non-null  object
 6   country_code       36045 non-null  object
 7   state_code         36045 non-null  object
 8   region             36045 non-null  object
 9   city               36045 non-null  object
 10  funding_rounds     36045 non-null  int64
 11  founded_at         36045 non-null  object
 12  first_funding_at   36045 non-null  object
 13  last_funding_at    36045 non-null  object
dtypes: int64(2), object(12)
memory usage: 3.9+ MB

### Investment

In [ ]:
investments.head()

                  company_permalink  ... raised_amount_usd
0             /organization/0-6-com  ...         2000000.0
1    /organization/004-technologies  ...               NaN
2  /organization/01games-technology  ...           41250.0
3              /organization/0xdata  ...        20000000.0
4              /organization/0xdata  ...         3000000.0

[5 rows x 18 columns]

In [ ]:
investments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168647 entries, 0 to 168646
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   company_permalink        168647 non-null  object
 1   company_name             168646 non-null  object
 2   company_category_list    165015 non-null  object
 3   company_country_code     158126 non-null  object
 4   company_state_code       155216 non-null  object
 5   company_region           156162 non-null  object
 6   company_city             156164 non-null  object
 7   investor_permalink       168635 non-null  object
 8   investor_name            168635 non-null  object
 9   investor_country_code    137708 non-null  object
 10  investor_state_code      123908 non-null  object
 11  investor_region          125430 non-null  object
 12  investor_city            136483 non-null  object
 13  funding_round_permalink  168647 non-null  object
 14  funding_round_type       168647 non-null  object
 15  funding_round_code       81062 non-null   object
 16  funded_at                168647 non-null  object
 17  raised_amount_usd        147028 non-null  float64
dtypes: float64(1), object(17)
memory usage: 23.2+ MB

In [ ]:
# Drop all missing values
investments.dropna(inplace = True)

In [ ]:
investments = investments.reset_index(drop = True)

In [ ]:
investments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59417 entries, 0 to 59416
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   company_permalink        59417 non-null  object
 1   company_name             59417 non-null  object
 2   company_category_list    59417 non-null  object
 3   company_country_code     59417 non-null  object
 4   company_state_code       59417 non-null  object
 5   company_region           59417 non-null  object
 6   company_city             59417 non-null  object
 7   investor_permalink       59417 non-null  object
 8   investor_name            59417 non-null  object
 9   investor_country_code    59417 non-null  object
 10  investor_state_code      59417 non-null  object
 11  investor_region          59417 non-null  object
 12  investor_city            59417 non-null  object
 13  funding_round_permalink  59417 non-null  object
 14  funding_round_type       59417 non-null  object
 15  funding_round_code       59417 non-null  object
 16  funded_at                59417 non-null  object
 17  raised_amount_usd        59417 non-null  float64
dtypes: float64(1), object(17)
memory usage: 8.2+ MB

## Exploratory Data Analysis

In [ ]:
companies.head()

                             permalink  ... last_funding_at
0               /organization/-qounter  ...      2014-10-14
1                /organization/0-6-com  ...      2008-03-19
2  /organization/0ndine-biomedical-inc  ...      2009-12-21
3                 /organization/0xdata  ...      2015-11-09
4                      /organization/1  ...      2014-02-05

[5 rows x 14 columns]

**1) What were the common company type that had raised money?**

In [ ]:
companies[['name', 'category_list']].groupby('category_list').count().rename(columns={'name': 'count'})

                                                    count
category_list
3D Printing                                             8
3D Printing|3D Technology                               1
3D Printing|3D Technology|Android|Artificial In...      1
3D Printing|3D Technology|Android|Games|iOS|Mob...      1
3D Printing|3D Technology|Audio|Mass Customization      1
...                                                   ...
iPhone|Software                                         1
mHealth                                                 1
mHealth|Mobile                                          1
mHealth|Software                                        1
mHealth|Software|Therapeutics                           1

[17480 rows x 1 columns]

**There are many but it does not answer the question. All I can see is that most of the sponsored companies are in the Technology sector. Now I will try to list some of the popular Technology trends to check if it is the main cause that the investors are pouring money into.**

In [ ]:
from collections import Counter
Counter(" ".join(companies['category_list']).split()).most_common(10)

[('Software', 3979),
 ('and', 2364),
 ('Biotechnology', 2044),
 ('Media', 1815),
 ('Health', 1667),
 ('Curated', 1355),
 ('+', 1113),
 ('Enterprise', 973),
 ('Care', 950),
 ('Technology', 921)]

**In short, Software is the main sector. In addition, the healhcare technology sector seemed to be attracting interest from investors.**

**2) Count the status of each company in USA**

In [ ]:
companies[companies['country_code'] == 'USA'][['name', 'country_code', 'status']].groupby(['country_code', 'status']).count()

                         name
country_code status
USA          acquired    2810
             closed      1649
             ipo          798
             operating  18896

**3) Which city in US that had most startups?**

In [ ]:
companies[companies['country_code'] == 'USA'][['name', 'city']].groupby('city').count().rename(columns={'name': 'count'}).sort_values(by = ['count'], ascending = False)

                   count
city
San Francisco       2564
New York            2294
Seattle              556
Austin               533
Palo Alto            520
...                  ...
Linthicum Heights      1
Litchfield             1
Little Elm             1
Little River           1
Zionsville             1

[1831 rows x 1 columns]

**Based on the result, most start ups are in Silicon Valley**

In [ ]:
investments.head()

       company_permalink company_name  ...   funded_at raised_amount_usd
0  /organization/0-6-com      0-6.com  ...  2008-03-19         2000000.0
1   /organization/0xdata       H2O.ai  ...  2015-11-09        20000000.0
2   /organization/0xdata       H2O.ai  ...  2015-11-09        20000000.0
3   /organization/0xdata       H2O.ai  ...  2014-07-19         8900000.0
4   /organization/0xdata       H2O.ai  ...  2015-11-09        20000000.0

[5 rows x 18 columns]

**4) List all companies and their investors**

In [ ]:
investments[['company_name', 'investor_name']].groupby(['company_name', 'investor_name']).count()

Empty DataFrame
Columns: []
Index: [(0-6.com, DT Capital Partners), (1-Page, Blumberg Capital), (1-Page, Georgetown Angels), (1-Page, Rothenberg Ventures), (1-Page, Satori Capital), (1000memories, FLOODGATE), (1000memories, Felicis Ventures), (1000memories, Founder Collective), (1000memories, Greylock Partners), (1000memories, Signatures Capital), (1001pharmacies.com, CM-CIC Capital Prive), (1006.tv, ClearVue Partners), (1006.tv, Sequoia Capital), (10X Genomics, Foresite Capital), (10X Genomics, Paladin Capital Group), (10X Genomics, Venrock), (117go, Softbank China Venture Capital), (12cm, Capstone Partners Korea), (1366 Technologies, Haiyin Capital), (1366 Technologies, Hanwha Chemical Corporation), (1366 Technologies, North Bridge Venture Partners & Growth Equity), (1366 Technologies, Polaris Partners), (1366 Technologies, VantagePoint Capital Partners), (1366 Technologies, Vorndran Mannheims Capital), (140 Proof, BlueRun Ventures), (140 Proof, SV Angel), (16WiFi, Baidu), (170 Systems, Polaris Partners), (17hats, Wavemaker Partners), (17u.cn, Boyu Capital), (17u.cn, Oriza Holdings), (17zuoye, DST Global), (17zuoye, Shunwei Capital), (17zuoye, Tiger Global Management), (19pay, Sequoia Capital), (19pay, Zero2IPO Ventures), (1Life Healthcare, Benchmark), (1Life Healthcare, DAG Ventures), (1Life Healthcare, Google Ventures), (1Life Healthcare, Maverick Capital), (1Life Healthcare, Oak Investment Partners), (1World Online, DEFTA Partners), (1World Online, GVA LaunchGurus Fund 1 L.P.), (1jiajie, Tencent Holdings), (1stdibs, Alibaba), (2 Minutes, Alliance Entreprendre), (2080 Media, BIP Capital), (2080 Media, Hamilton Ventures LLC), (2080 Media, Imlay Investments), (2080 Media, Noro-Moseley Partners), (20x200, AOL Ventures), (20x200, Founder Collective), (20x200, SV Angel), (20x200, True Ventures), (21 Inc, Winklevoss Capital), (21Diamonds, MCI Capital SA), (21Diamonds, Ventech), (23andMe, Casdin Capital), (23andMe, Genentech), (23andMe, Google), (23andMe, Google Ventures), (23andMe, Johnson & Johnson Development Corporation), (23andMe, MPM Capital), (23andMe, Mohr Davidow Ventures), (23andMe, New Enterprise Associates), (23andMe, Stephens Investment Management), (23andMe, Xfund), (24M Technologies, CRV), (24M Technologies, North Bridge Venture Partners & Growth Equity), (24M Technologies, U.S. Department of Energy), (2Checkout, Chicago Growth Partners), (2Checkout, Trident Capital), (2U Inc., Bessemer Venture Partners), (2U Inc., City Light Capital), (2U Inc., Highland Capital Partners), (2U Inc., Hillman Ventures), (2U Inc., Novak Biddle Venture Partners), (2U Inc., Redpoint Ventures), (2U Inc., Rethink Education), (2Wire, Accel), (2Wire, DCM), (2Wire, Dell), (2Wire, GGV Capital), (2Wire, Invesco Perpetual), (2Wire, Meritech Capital Partners), (2Wire, Oak Investment Partners), (2Wire, Shell Internet Ventures B.V), (2Wire, Technology Crossover Ventures), (2Wire, Venrock), (2Wire, Weber Capital), (2can, Almaz Capital), (2can, ESN Group), (2can, Inventure Partners), (2houses, Inventures SA), (2houses, Mymicroinvest), (2nd Watch, Columbia Capital), (2nd Watch, Madrona Venture Group), (2nd Watch, Top Tier Capital Partners), (3-V Biosciences, Kleiner Perkins Caufield & Byers), (3-V Biosciences, New Enterprise Associates), ...]

[42778 rows x 0 columns]

**5) Top 10 funding totals raised by Company**

In [ ]:
investments[['company_name', 'raised_amount_usd']].groupby('company_name').sum().rename(columns={'raised_amount_usd': 'Funding sum'}).sort_values(by = ['Funding sum'], ascending = False).head(10)

                                 Funding sum
company_name
Uber                            2.457200e+10
Flipkart                        1.241100e+10
Groupon                         1.013480e+10
MediaVast                       9.430000e+09
SoFi                            8.603600e+09
Pinterest                       6.840000e+09
Ola                             5.779500e+09
Spotify                         5.777280e+09
Lyft                            5.694000e+09
Space Exploration Technologies  5.270870e+09

**6) Top 10 funding totals raised by Company Category**

In [ ]:
investments[['company_category_list', 'raised_amount_usd']].groupby('company_category_list').sum().rename(columns={'raised_amount_usd': 'Funding sum'}).sort_values(by = ['Funding sum'], ascending = False).head(10)

                                                     Funding sum
company_category_list
Biotechnology                                       1.402629e+11
Software                                            4.462226e+10
Health Care                                         2.989893e+10
Clean Technology                                    2.883782e+10
Biotechnology|Health Care                           2.520652e+10
Semiconductors                                      2.493012e+10
Automotive|Design|Limousines|Public Transportat...  2.457200e+10
Enterprise Software                                 2.356475e+10
E-Commerce                                          2.002801e+10
Mobile                                              1.591148e+10

**7) Top 10 acquisitions by Company and Acquirer**

In [ ]:
acquisitions[['company_name', 'acquirer_name', 'acquired_at', 'price_amount']].sort_values(by = ['price_amount'], ascending = False).head(10).reset_index(drop = True)

        company_name  ...  price_amount
0           Allergan  ...  1.600000e+11
1           Allergan  ...  7.050000e+10
2      SABMiller PLC  ...  6.800000e+10
3                EMC  ...  6.700000e+10
4           Bank One  ...  5.800000e+10
5  Time Warner Cable  ...  5.600000e+10
6              Cigna  ...  5.420000e+10
7            DIRECTV  ...  4.850000e+10
8           Covidien  ...  4.800000e+10
9  Time Warner Cable  ...  4.500000e+10

[10 rows x 4 columns]